runtime: php73
api_version: 1

handlers:
- url: /
  script: index.blade.php

# - url: /stylesheets
#   static_dir: stylesheets

# - url: /(.*\.(gif|png|jpg))$
#   static_files: static/\1
#   upload: static/.*\.(gif|png|jpg)$

